//App actions
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

//House audit actions
export const FETCH_HOUSE_AUDITS = 'FETCH_HOUSE_AUDITS';
export const FETCH_HOUSE_AUDIT = 'FETCH_HOUSE_AUDIT';
export const CREATE_HOUSE_AUDIT = 'CREATE_HOUSE_AUDIT';
export const DELETE_HOUSE_AUDIT = 'DELETE_HOUSE_AUDIT';
export const EDIT_HOUSE_AUDIT = 'EDIT_HOUSE_AUDIT';

// House Audit Details
export const GET_HOUSE_AUDIT_TEMPLATE = 'GET_HOUSE_AUDIT_TEMPLATE';
export const HOUSE_AUDIT_ITEM_CHANGE = 'HOUSE_AUDIT_ITEM_CHANGE';
export const HOUSE_AUDIT_FIELD_CHANGE = 'HOUSE_AUDIT_FIELD_CHANGE';
export const HOUSE_AUDIT_FINDING_CHANGE = 'HOUSE_AUDIT_FINDING_CHANGE';

//Other actions
export const ANOTHER_ACTION = 'ANOTHER_ACTION';
